client/config/routes.rb
Rails.application.routes.draw do

  resources :test_objects

end

client/app/models/authenticator.rb
# encoding: utf-8
# frozen_string_literal: true
class Authenticator
  def self.current_token
    if CONFIG[:token].blank?
      url =  'http://localhost:3000/login/login'
      uri = URI.parse(url)
      result = ''
      Net::HTTP.start(uri.host, uri.port) do |http|
        result = handle_request(http, uri)
      end
      CONFIG[:token] = result['token']
    end
    CONFIG[:token]
  end

  class << self
    private

    def handle_request(http, uri, params = {}.to_json)
      request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
      request.body = params
      response = http.request request

      case response
        when Net::HTTPSuccess then
          JSON.parse(response.body)
        when Net::HTTPUnauthorized then
          raise 'Unauthorized'
        else
          raise
      end
    end
  end
end

client/app/models/test_object.rb
class TestObject < ActiveResource::Base
  self.site = 'http://localhost:3000'
  headers['Authorization'] = "Token token=\"#{Authenticator.current_token}\""
end

client/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

client/app/controllers/test_objects_controller.rb
class TestObjectsController < ApplicationController
  before_action :set_test_object, only: [:show, :edit, :update, :destroy]

  # GET /test_objects
  # GET /test_objects.json
  def index
    @test_objects = TestObject.all
  end

  # GET /test_objects/1
  # GET /test_objects/1.json
  def show
  end

  # GET /test_objects/new
  def new
    @test_object = TestObject.new
  end

  # GET /test_objects/1/edit
  def edit
  end

  # POST /test_objects
  # POST /test_objects.json
  def create
    @test_object = TestObject.new(test_object_params)

    respond_to do |format|
      if @test_object.save
        format.html { redirect_to @test_object, notice: 'Test object was successfully created.' }
        format.json { render :show, status: :created, location: @test_object }
      else
        format.html { render :new }
        format.json { render json: @test_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_objects/1
  # PATCH/PUT /test_objects/1.json
  def update
    respond_to do |format|
      if @test_object.update(test_object_params)
        format.html { redirect_to @test_object, notice: 'Test object was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_object }
      else
        format.html { render :edit }
        format.json { render json: @test_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_objects/1
  # DELETE /test_objects/1.json
  def destroy
    @test_object.destroy
    respond_to do |format|
      format.html { redirect_to test_objects_url, notice: 'Test object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_object
      @test_object = TestObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_object_params
      params.require(:test_object).permit(:value)
    end
end

client/app/helpers/application_helper.rb
module ApplicationHelper
end

client/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Client</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

client/app/views/test_objects/_form.html.erb
<%= form_for(@test_object) do |f| %>
  <% if @test_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_object.errors.count, "error") %> prohibited this test_object from being saved:</h2>

      <ul>
      <% @test_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

client/app/views/test_objects/edit.html.erb
<h1>Editing Test Object</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_object %> |
<%= link_to 'Back', test_objects_path %>

client/app/views/test_objects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Test Objects</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_objects.each do |test_object| %>
      <tr>
        <td><%= test_object.value %></td>
        <td><%= link_to 'Show', test_object %></td>
        <td><%= link_to 'Edit', edit_test_object_path(test_object) %></td>
        <td><%= link_to 'Destroy', test_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test object', new_test_object_path %>

client/app/views/test_objects/new.html.erb
<h1>New Test Object</h1>

<%= render 'form' %>

<%= link_to 'Back', test_objects_path %>

client/app/views/test_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @test_object.value %>
</p>

<%= link_to 'Edit', edit_test_object_path(@test_object) %> |
<%= link_to 'Back', test_objects_path %>